### ISSUE TITLE
a element with a href, and button role

### ISSUE THREAD

**Issue by jongund** [webspecs/html-aria#5]
In the "Requirements for implementers" section it talks about not using a button role on an "a" element with an href attribute.  But the spec says the "button' role is allowed on an "a" element with a href.  

The example or the spec should be updated to be consistent?
or
Is part of the process to come up with "authoring" practices/guidance like the example, even though the spec allows the button role on an a element.

**Comment by stevefaulkner** [comment]
@jongund "The example or the spec should be updated to be consistent?" Example needs update.

**Comment by jongund** [comment]
Do you think it is a good idea for people to override the "a" element with role=button?
Should it be "recommended" to authors use a button element or input[type="button"] instead of a[role="button"]?

**Comment by skifte** [comment]
A possible scenario / corner case where role="button" _might_ be useful on a-elements: Let's say you have some "call to action" links, styled to look like fancy buttons (for example using the Bootstrap .btn class, or similar), and a person using voice commands wants to access them. He might say "click button <name>", and then maybe nothing happens? I'm on thin ice here, since I have little experience with voice recognition software, but at least dragon naturally speaking seems to support some aria roles  (http://simplyaccessible.com/article/dragon-aria/).

**Comment by stevefaulkner** [comment]
@jongund 
>Do you think it is a good idea for people to override the "a" element with role=button?
Should it be "recommended" to authors use a button element or input[type="button"] instead of a[role="button"]?

I don't personally think its a good idea, but it is a common pattern and there is no way to force devs to use the most appropriate element, hence part of the need for ARIA. There is no normative SHOULD NOT or MUST NOT on use of <a role=button>, the text in the implementer section was old and incorrect in its use as an example. I have removed the text for now.

**Comment by stevefaulkner** [comment]
@skifte thanks for the input.
